### PR TITLE
Fixed the FileWrittenEvent having the wrong path

### PR DESCRIPTION
**Pull request by dprotaso**
if the writer had a suffix or prefix.

### CODE REVIEW

**Comment by jvalkeal** [comment]
@dprotaso trying to get this into next release, so that's for the PR. Would you mind signing our CLA https://support.springsource.com/spring_committer_signup if you haven't done it already?

**Comment by jvalkeal** [comment]
@dprotaso just realized you don't need to sign cla.

**Comment by jvalkeal** [comment]
Merged with https://github.com/spring-projects/spring-hadoop/commit/7e280c2d06564cd951c0160a0c18f0e914f9bb8c

**Comment by dprotaso** [comment]
Because I work for Pivotal?

**Comment by jvalkeal** [comment]
@dprotaso yes we don't need to sign cla

**Pull request closed without merging**
